logging:
  level:
    root: warn
    '[org.jmresler.studies.kanban]': debug
  file:
    name: logs/${spring.application.name}.log

management:
  endpoints:
    enabled-by-default: true
    jmx:
      exposure:
        include:
          - env
  security:
    enabled: false

server:
  port: 8090
  servlet:
    context-path: /v1/${spring.application.name}
    
spring:
  application:
    name: kanban
  batch:
    jdbc:
      initialize-schema: ALWAYS
  datasource:
    batch:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:file:./data/batch-db;mode=DB2
      username: app
      password: app
      hikari:
        transaction-isolation: TRANSACTION_READ_UNCOMMITTED
    aw:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:file:./data/aw-db;mode=DB2
      username: app
      password: app
      hikari:
        transaction-isolation: TRANSACTION_READ_UNCOMMITTED
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true